BugTracker/urls.py
from django.conf.urls import url, patterns
from BugTracker.views import *

urlpatterns = patterns('',
    url('^$',  BugView.as_view(),name='BugView'),
    url('^CreateBug/$','BugTracker.views.RaiseABug', name='CreateBug'),
    url('^UploadImages/$',  'BugTracker.views.upload_file' ,name='UploadImages'),
    url('^DeleteFileUploads/$',  'BugTracker.views.DeleteFileUploads' ,name='DeleteFileUploads'),



)

TeamTrack/urls.py
from django.conf.urls import patterns, include, url
from tastypie.api import Api

from Services import *


v1_api = Api(api_name='v1')
v1_api.register(TasksResource())
v1_api.register(UserResource())
v1_api.register(ProjectsResource())
v1_api.register(LeavesResource())

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

def if_installed(appname, *args, **kwargs):
    import settings
    ret = url(*args, **kwargs)
    if appname not in settings.INSTALLED_APPS:
        ret.resolve = lambda *args: None
    return ret

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
    # url(r'^TaskManager/', include('TaskManager.urls')),
    # url(r'^LeaveManager/', include('LeaveManager.urls')),
    # url(r'^BugTracker/', include('BugTracker.urls')),
    if_installed('TaskManager', r'^TaskManager/', include('TaskManager.urls')),
    if_installed('LeaveManager', r'^LeaveManager/', include('LeaveManager.urls')),
    if_installed('BugTracker', r'^BugTracker/', include('BugTracker.urls')),
)


    # AppsList = []
    # with open(os.path.abspath("TaskManager/static/Config/Applications.json")) as f:
    #     jsonContent = json.load(f)
    #     for item in jsonContent["Apps"]:
    #         AppsList.append(item)
    # patterns('')
    # TeamTrack += tuple(AppsList)
    # settings.INSTALLED_APPS += tuple(AppsList)

BugTracker/models.py
from django.db import models
from TaskManager.models import ExtendedUser, Tasks
from django.contrib.auth.models import User
# Create your models here.

class Bug(models.Model):
    title = models.CharField(max_length=150)
    taskid = models.ForeignKey(Tasks, db_column='TaskId') # Field name made lowercase.
    description = models.TextField()
    status = models.CharField(max_length=50)
    owner = models.ForeignKey(ExtendedUser)
    def __unicode__(self):
        return "%s" % self.title

class BugScreenShots(models.Model):
    imageId = models.ForeignKey(Bug, db_column='imageId')
    imageName = models.CharField(max_length=50)
    imagePath = models.CharField(max_length=350)
    CreateDate = models.DateTimeField()
    ModifiedDate = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s" % self.imageName

class BugComments(models.Model):
    CommentId = models.ForeignKey(Bug)
    Comment = models.TextField()
    def __unicode__(self):
        return "%s"%self.CommentId

BugTracker/forms.py
from django import forms
from TaskManager.models import Projects, ExtendedUser, Tasks

class CreateBugForm(forms.Form):
    Title = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Title'}))
    TaskId = forms.ModelChoiceField(label='', queryset=Tasks.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))
    Description = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder':'What Happened ?'}))
    UserId = forms.ModelChoiceField(label='', queryset=ExtendedUser.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))

BugTracker/views.py
# Create your views here.
from django.views.generic.base import TemplateView
from BugTracker.forms import CreateBugForm
from BugTracker.models import Bug, BugScreenShots
from TaskManager.models import Tasks, TaskStatus, TaskmanagerTasktimeline, ExtendedUser
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
import datetime
from TeamTrack.settings import STATIC_URL
import logging
import os
import json
import redis
log = logging.getLogger(__name__)
from mimetypes import MimeTypes

class BugView(TemplateView):
    template_name = "bugs.html"

    def get_context_data(self, **kwargs):
        context = super(BugView, self).get_context_data(**kwargs)
        context['BugForm'] = CreateBugForm()
        context['Bugs'] = Bug.objects.all()
        return context

def RaiseABug(request):
    try:
        obj = Tasks.objects.get(pk=request.POST['TaskId'])
        obj.Status = TaskStatus.objects.get(pk=3)
        BugObj = Bug(title=request.POST['Title'], taskid=obj, description=request.POST['Description'], status=obj.Status, owner=ExtendedUser.objects.get(pk=request.user))
        BugObj.save()
        obj.save()
        project = obj.ProjectId
        timelineObj = TaskmanagerTasktimeline(project=project, title=request.POST['Title'], taskid=obj, status=obj.Status, owner=ExtendedUser.objects.get(pk=request.user.id), notes=request.POST['Description'], timelineCheck="b")
        timelineObj.save()

        r = redis.StrictRedis(host='localhost', port=6379, db=0)
        redisNotiObj = {}
        redisNotiArr = []
        redisNotiObj["Notify"] = "%s"%request.user
        redisNotiObj["Message"] = "A new Bug was raised"
        redisNotiObj["Type"] = 2
        redisNotiObj["Link"] = "%s"%reverse('CreateBug')
        redisNotiArr.append(redisNotiObj)
        r.publish('chat', json.dumps(redisNotiObj))
        return HttpResponse("success")
    except Exception as ex:
        log.exception(ex)
        return HttpResponse(ex)

def upload_file(request):
    file = request.FILES['file']
    fileName = request.FILES['file'].name
    curUser = request.user
    newFileName = "%s_%s" % (curUser, fileName)
    handle_uploaded_file(file, newFileName)
    return HttpResponseRedirect(reverse('BugView'))


def handle_uploaded_file(f, FName):
    with open('D:/Work/Projects/Python/TeamTrack/BugTracker/BugScreenshotsTemp/%s' % FName, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

def DeleteFileUploads(request):
    arr = request.POST.getlist('arr[]')
    curUser = request.user
    for item in arr:
        file_path = 'D:/Work/Projects/Python/TeamTrack/BugTracker/BugScreenshotsTemp/%s_%s' % (curUser, item)
        try:
            if os.path.isfile(file_path):
                os.unlink(file_path)
        except Exception as ex:
            return HttpResponse(ex)
    return HttpResponse("Success")

BugTracker/templates/bugs.html
{% extends "base.html" %}
{% load static %}
{% load apptags %}

        {% block MainBodyWrapper %}


            </br>


            <div class="row">
                <div class="col-lg-12">
                    <div >
                        <h1 class="page-header">
                            Bugs
                        </h1>
                         <ol class="breadcrumb">
                      <li><a href="{% url 'home' %}">Home</a></li>
                      <li class="active">Bugs</li>
                    </ol>

                    </div>

                </div>

                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Create Bug
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">

                        {{ BugForm.as_p }}
                            <div class="progress-button">
                            <button id="CreateBug"><span>Create Bug</span></button>
                            <svg class="progress-circle" width="70" height="70"><path d="m35,2.5c17.955803,0 32.5,14.544199 32.5,32.5c0,17.955803 -14.544197,32.5 -32.5,32.5c-17.955803,0 -32.5,-14.544197 -32.5,-32.5c0,-17.955801 14.544197,-32.5 32.5,-32.5z"/></svg>
                            <svg class="checkmark" width="70" height="70"><path d="m31.5,46.5l15.3,-23.2"/><path d="m31.5,46.5l-8.5,-7.1"/></svg>
                            <svg class="cross" width="70" height="70"><path d="m35,35l-9.3,-9.3"/><path d="m35,35l9.3,9.3"/><path d="m35,35l-9.3,9.3"/><path d="m35,35l9.3,-9.3"/></svg>
                            </div>

                            </div>

                </div>
                </div>
                <div class="col-lg-8" style="padding-left:15px;">
                     <div class="panel panel-default">
                         <div class="panel-heading">
                            Screenshots<span id="DeleteUploads" style="cursor:pointer" class="fa arrow"></span>
                        </div>
                        <div class="panel-body" id="DropzoneDiv" style="min-height: 400px;" >
                             <form action="{% url 'UploadImages' %}" class="dropzone" id="my-awesome-dropzone">{% csrf_token %}
                             </form>
                        </div>
                      </div>
                </div>
            </div>

            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            To Do
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table" id="dataTables-example">
                                    <thead>

                                        <tr>
                                            <th>Title</th>
                                            <th><select class="form-control filterOption" value="1">{% getDataIntoOptions 'tas' %}</select></th>
                                            <th><select class="form-control filterOption" value="2">{% getDataIntoOptions 'pro' %}</select></th>
                                            <th><select class="form-control filterOption" value="3">{% getDataIntoOptions 'usr' %}</select></th>
                                            <th><select class="form-control filterOption" value="4">{% getDataIntoOptions 'sta' %}</select></th>
                                            <th>Details</th>
                                            <th>Progress</th>
                                        </tr>

                                    </thead>
                                    <tbody>
                                        {% for Task in Bugs %}
                                       <tr>

                                            <td>{{ Task.title }}</td>
                                            <td>{{ Task.taskid.TaskTitle }}</td>
                                           <td>{{ Task.taskid.ProjectId.Title }}</td>
                                            <td>{{ Task.owner }}</td>
                                            <td>{{ Task.status }}</td>


                                           <td><a href="{% url 'tasksdetail' Task.taskid.id %}">View</a></td>
                                           <td>
                                           <div class="progress progress-striped active">
                                                {% if Task.status.id == 1 %}
                                                <div id="ProgressBar" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                                </div>
                                                {% elif Task.status.id == 2 %}
                                                <div id="ProgressBar" class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                                </div>
                                                {% elif Task.status.id == 3 %}
                                                <div id="ProgressBar" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                                </div>
                                                {% elif Task.status.id == 4 %}
                                                <div id="ProgressBar" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%">
                                                </div>
                                                {% endif %}
                                            </div>
                                           </td>

                                        </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div>

                            <!-- /.table-responsive -->

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->

            </div>
            <!-- /.row -->
             <div class="row">
                 <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Donut Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="morris-donut-chart"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                 </div>
                 <!-- /.row -->


    <Link rel="stylesheet" href="{% static "css/Dropzone.css" %}">


    <script src="{% static "js/plugins/dataTables/jquery.dataTables.js" %}"></script>
    <script src="{% static "js/plugins/dataTables/dataTables.bootstrap.js" %}"></script>



    <script src='{% static 'js/plugins/morris/raphael-2.1.0.min.js' %}'></script>
     <script src='{% static 'js/plugins/morris/morris.js' %}'></script>
    <script src="{% static "js/Dropzone.js" %}"></script>

    <script>
    $(document).ready(function() {



        $("#bugsTab").addClass("Active")
        $("#bugsTab a").bind('click', false);
        //$('#dataTables-example').dataTable();

        $(".filterOption").change(function(){
            var SelectedTag = $(this).val()
            var SelectedColumn = $(this).attr("value")
            tblFilter('dataTables-example', SelectedTag, SelectedColumn)

        })
        $('#my-awesome-dropzone').hide();
        $("#id_TaskId, #id_UserId").bind('change keyup',function(){$("#DeleteUploads").click(); Validate()})
        $("#id_Description").keyup(function(){Validate()})
        function Validate()
        {
            if($("#id_TaskId").val() != "" && $("#id_Description").val() != "" && $("#id_UserId").val()!="")
            {
                $('#my-awesome-dropzone').fadeIn();
            }
            else
            {
                $('#my-awesome-dropzone').fadeOut();
            }

        }


        $("#DeleteUploads").click(function(){
            var arrayList = []
            $("#my-awesome-dropzone div.dz-preview").each(function(){
                arrayList.push($(this).children('div.dz-details').children('div.dz-filename').children('span').html())
            })
            var arr = {"arr": arrayList, "csrfmiddlewaretoken": "{{ csrf_token }}"}
            $.ajax({
                url:"{% url 'DeleteFileUploads' %}",
                type:"post",
                data:arr,
                success: function(dat){ Notify();$(".icon").slideUp(5000);$(".dz-preview").remove() },
                error: function(dat){alert(JSON.stringify(dat))}
            })
        })

        function tblFilter(tableId, tag, columnNo)
        {
            $('#'+tableId+' tr').each(function() {
                    if($(this).find("td").eq(columnNo).html() != null)
                    {
                        $(this).show();

                    }
                });

            $(".filterOption").each(function(){
                var SelectedTag = $(this).val()
                var SelectedColumn = $(this).attr("value")
                if(SelectedTag != "No Filter")
                {
                    $('#'+tableId+' tr').each(function() {
                        if($(this).find("td").eq(SelectedColumn).html() != null)
                        {
                            if($(this).find("td").eq(SelectedColumn).html() != SelectedTag)
                            {
                                $(this).hide();
                            }
                        }
                    });
                }
            })



        }




    });
    </script>
{% endblock MainBodyWrapper %}